datasource:
  default: ${APP_ENV}
  #В Makefile определяем (через переменную APP_ENV) к какой базе подключаемся:
  #Локально "development" - к H2, а в продакшене "production" – к PostgreSQL.
  development:
    username: ""
    password: ""
    url: "jdbc:h2:./database"
  production:
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    url: ${JDBC_DATABASE_URL}

ebean:
  development:
    migration:
      run: false
  production:
    migration:
      run: true
